// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coinly;

#nullable disable

namespace coinly.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250208103000_SeedAccountsData")]
    partial class SeedAccountsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("coinly.Models.Account", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("balance")
                        .HasColumnType("REAL");

                    b.Property<float>("expense")
                        .HasColumnType("REAL");

                    b.Property<float>("income")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            id = 1,
                            balance = 4000f,
                            expense = 6000f,
                            income = 10000f
                        },
                        new
                        {
                            id = 2,
                            balance = 10000f,
                            expense = 10000f,
                            income = 20000f
                        },
                        new
                        {
                            id = 3,
                            balance = 10000f,
                            expense = 20000f,
                            income = 30000f
                        });
                });

            modelBuilder.Entity("coinly.Models.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("accountId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("amount")
                        .HasColumnType("REAL");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("merchant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("coinly.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
